// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-echarts/src/BarEchart.vue')['default']
    BaseEchart: typeof import('./src/components/page-echarts/src/BaseEchart.vue')['default']
    BreadCrumb: typeof import('./src/components/main-header/cpns/BreadCrumb.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LineEchart: typeof import('./src/components/page-echarts/src/LineEchart.vue')['default']
    MainHeader: typeof import('./src/components/main-header/MainHeader.vue')['default']
    MainMenu: typeof import('./src/components/main-menu/MainMenu.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/MapEchart.vue')['default']
    PageContent: typeof import('./src/components/page-content/PageContent.vue')['default']
    PageModal: typeof import('./src/components/page-modal/PageModal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/PageSearch.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/PieEchart.vue')['default']
    RoseEchart: typeof import('./src/components/page-echarts/src/RoseEchart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserState: typeof import('./src/components/main-header/cpns/UserState.vue')['default']
  }
}
